#!/bin/bash

set -e

RIGGER_HOME=$(dirname $(realpath $0))
cd $RIGGER_HOME

if [ -z $NO_PULL ]
then
    git pull
fi

for dir in $(find $RIGGER_HOME -maxdepth 1 -type d -name "job-*" | sort)
do
    echo Starting $dir  

    cd $dir

    set +e
    ./try
    ERROR=$?
    set -e

    if [ $ERROR != "0" ]
    then
        echo Last job failed with code $ERROR

        if [ -f ./catch ]
        then
            env ERROR=$ERROR ./catch
        fi
        
        exit 1
    fi

    cd $RIGGER_HOME

    if [ -z $NO_DELETE ]
    then
        rm $dir -rf
    fi

done

echo All done.
