#!/bin/bash

set -e

if [ -z "$NO_CLONE" ]
then
    cd /host/opt
    git clone https://github.com/device-farm/rigger.git
fi

ln -sf /opt/rigger/check /host/etc/cron.hourly/rigger

echo Rigger installed.